### ISSUE TITLE
Container closes after a few seconds

### ISSUE THREAD

**Issue by madic-creates** [Stanback/alpine-samba#1]
Hey, I'm trying your docker image but on my host, it's always closing after a few seconds.
The command line I use:
docker run \
  -p 192.168.1.42:445:445 \
  -d \
  --name=samba \
  --label namespace=Fileserver \
  stanback/alpine-samba:latest

Also the same if I mount a smb.conf
docker run \
  -v /vol_raidz1/docker/persistend/samba/smb.conf:/etc/samba/smb.conf \
  -p 192.168.1.42:445:445 \
  -d \
  --name=samba \
  --label namespace=Fileserver \
  stanback/alpine-samba:latest

Any ide why this happens?

**Comment by madic-creates** [comment]
I missed the -t for the tty -_- Found it directly after opening the ticket. Thank you for your docker file and explanations :)

**Comment by Stanback** [comment]
@Madic- No problem, glad it's working for you!
